// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYdjQrHpRdemwonAULwWa2DbVCIdmz964',
    appId: '1:78473985591:web:2609edad2aa8c86b6b09b2',
    messagingSenderId: '78473985591',
    projectId: 'homesense-ai',
    authDomain: 'homesense-ai.firebaseapp.com',
    databaseURL: 'https://homesense-ai-default-rtdb.firebaseio.com',
    storageBucket: 'homesense-ai.firebasestorage.app',
    measurementId: 'G-PGW77KH7CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAceI6b6_ZylNO6jWUTE2AT_ecnQkYUVnk',
    appId: '1:78473985591:android:085b6d454413258e6b09b2',
    messagingSenderId: '78473985591',
    projectId: 'homesense-ai',
    databaseURL: 'https://homesense-ai-default-rtdb.firebaseio.com',
    storageBucket: 'homesense-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI8wJlw1Gi4E7xwhlLEJ8Z0ObjdzDEiS4',
    appId: '1:78473985591:ios:3ecacd8a5c579ff56b09b2',
    messagingSenderId: '78473985591',
    projectId: 'homesense-ai',
    databaseURL: 'https://homesense-ai-default-rtdb.firebaseio.com',
    storageBucket: 'homesense-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI8wJlw1Gi4E7xwhlLEJ8Z0ObjdzDEiS4',
    appId: '1:78473985591:ios:3ecacd8a5c579ff56b09b2',
    messagingSenderId: '78473985591',
    projectId: 'homesense-ai',
    databaseURL: 'https://homesense-ai-default-rtdb.firebaseio.com',
    storageBucket: 'homesense-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYdjQrHpRdemwonAULwWa2DbVCIdmz964',
    appId: '1:78473985591:web:802e057ffd6695946b09b2',
    messagingSenderId: '78473985591',
    projectId: 'homesense-ai',
    authDomain: 'homesense-ai.firebaseapp.com',
    databaseURL: 'https://homesense-ai-default-rtdb.firebaseio.com',
    storageBucket: 'homesense-ai.firebasestorage.app',
    measurementId: 'G-HSVM78FRCW',
  );
}
