name: flutter_application_1
description: "HomeSensor-AI — Smart IoT Mobile Dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.1

  # State Management & Utilities
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
